image: docker:stable

services:
  - docker:19.03.13-dind

stages:
  - build
  - deploy

variables:
  DOCKER_REGISTRY: registry.ezleads.io
  REPO_NAME: ambarmotors/ambarmotors-home
  TAG: ${CI_COMMIT_SHORT_SHA}
  CONTAINER_IMAGE: ${DOCKER_REGISTRY}/${REPO_NAME}:${CI_COMMIT_SHORT_SHA}
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

build-staging:
  stage: build
  script:
    - docker login ${DOCKER_REGISTRY} -u ${DOCKER_USER} -p ${DOCKER_PASSWORD}
    - docker pull ${DOCKER_REGISTRY}/${REPO_NAME}:latest || true
    - docker build -f Dockerfile-staging -t ${DOCKER_REGISTRY}/${REPO_NAME}:${TAG} .
    - docker push ${DOCKER_REGISTRY}/${REPO_NAME}:${TAG}
  only:
    - master

deploy to staging:
  stage: deploy
  image: dtzar/helm-kubectl
  script:
    - sed -i "s/<VERSION>/${TAG}/g" deployment-staging.yaml
    - kubectl delete -f deployment-staging.yaml || true
    - kubectl apply -f deployment-staging.yaml
  only:
    - master
